-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:



-- Exercise 1: Count the number of trips in January 2023


-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023


-- Exercise 3: Find the most popular pickup location


-- Exercise 4: Analyze the number of trips per hour of the day


-- Exercise 5: Calculate the average trip distance


-- Exercise 6: Find the longest trip by distance


-- Exercise 7: Calculate the total number of passengers by payment type


-- Exercise 8: Find the most common drop-off location for trips paid by credit card


-- Exercise 9: Calculate the total number of trips that had more than 4 passengers


-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance